name: Product_deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: self-hosted

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
    - uses: actions/checkout@v3
    - name: Directory Permissions
      run: |
        # Fix permissions for files and directories under the repositor
        sudo chown -R ubuntu:ubuntu /var/www/orbitnapp.com/pcatalog.orbitnapp.com/actions-runner/_work/product_catalog/product_catalog/
        sudo chmod -R 777 /var/www/orbitnapp.com/pcatalog.orbitnapp.com/actions-runner/_work/product_catalog/product_catalog/
    - name: Clear cache directory
      run: |
        # Clear the cache directory to avoid issues with stale files
        sudo rm -rf /var/www/orbitnapp.com/pcatalog.orbitnapp.com/actions-runner/_work/product_catalog/product_catalog/storage/*
        sudo chown -R ubuntu:ubuntu /var/www/orbitnapp.com/pcatalog.orbitnapp.com/actions-runner/_work/product_catalog/product_catalog/storage
